var a = 10;
document.write("The value of a is " + a + "<br>");
document.write("The value of ++a is " + ++a + "<br>");
document.write("Now the value of a is" + a + "<br>");
document.write("The value of a++ is" + a++ + "<br>");
document.write("Now the value of a is" + a + "<br>");
document.write("The value of --a is " + --a + "<br>");
document.write("Now the value of a is " + a + "<br>");
document.write("The value of a-- is " + a-- + "<br>");
document.write("Now the value of a is " + a + "<br>");
